### ISSUE TITLE
Request for Gradle Version Update for background_locator_2 Compatibility with Flutter 3.29.2

### ISSUE THREAD

**Issue by spcodeworks** [Yukams/background_locator_fixed#146]
I am currently using the background_locator_2 package with Flutter 3.29.2 and SDK version 3.7.2. However, I have encountered an issue with the Gradle version used in the package. It is currently set to Gradle 7.6, which is causing compatibility errors with my project.
To resolve this issue, I would like to request an update to Gradle 8.10.2 to ensure compatibility with the current Flutter version and to avoid the errors that arise due to the older Gradle version.
Could you please provide guidance on how to update this or if there is a version of the package that already supports Gradle 8.10.2?

**Comment by bluMister** [comment]
there are multiple pull requests that fixes this, waiting to be accepted. Unfortunatelly there has been no progress in merging them for months now so the only thing you can do, is use a fork of this project where this is already implemented.

**Comment by devappsteam** [comment]
Adicione a correção efetuada pelo @sultan18kh ao seu pubspec.yaml

  ```
background_locator_2:
    git:
      url: https://github.com/sultan18kh/background_locator_2_gradle_migration.git
      ref: fix/gradle-compatibility
```
