### ISSUE TITLE
App freeze when launch after killing it

### ISSUE THREAD

**Issue by DmitriySimonov** [Yukams/background_locator_fixed#67]
https://github.com/Baseflow/flutter-geolocator/issues/1220
Same problem as here in your package

I am use flutter 3.7.5
i need this version of flutter
When can we expect an update so that everything works stably for the new flutter?

use:
```
 background_locator_2:
   git:
     url: https://github.com/tulioccalazans/background_locator_fixed.git
     ref: master
```
